### ISSUE TITLE
Provide Homebrew formula

### ISSUE THREAD

**Issue by florianrusch** [pulumi/tf2pulumi#111]
It would be nice, if the enduser could install and manage the `tf2pulumi` installation with homebrew on MacOS. (Like the Homebrew formula for Pulumi itself)

**Comment by jen20** [comment]
This formula 'works':

```ruby
class Tf2pulumi < Formula
  desc "Tool for migrating Terraform configurations to Pulumi"
  homepage "https://pulumi.io"
  url "https://github.com/pulumi/tf2pulumi.git",
    :tag      => "v0.5.1",
    :revision => "302ebabfb6e32f31adf49a2fc853d8b7f08a688f"

  depends_on "go" => :build

  def install
    ENV["GOPATH"] = buildpath
    ENV["GO111MODULE"] = "on"

    dir = buildpath/"src/github.com/pulumi/tf2pulumi"
    dir.install buildpath.children

    cd dir do
      system "go", "mod", "vendor"
      system "make", "dist"
      bin.install Dir["#{buildpath}/bin/*"]
      prefix.install_metafiles

      # Install bash completion
      output = Utils.popen_read("#{bin}/tf2pulumi gen-completion bash")
      (bash_completion/"pulumi").write output

      # Install zsh completion
      output = Utils.popen_read("#{bin}/tf2pulumi gen-completion zsh")
      (zsh_completion/"_pulumi").write output
    end
  end

  test do
    assert_equal "error: creating tree module: No Terraform configuration files found in directory: .",
      shell_output("#{bin}/tf2pulumi").strip
  end
end
```

However, there are a few issues:

- The 0.5.1 tag is no longer buildable because of the git.apache.org server being missing. We need to cut a new release, and I've opened #116 to upgrade to Go 1.13 at the same time.
- The repository does not meet the 'notability' requirements for including in Homebrew Core:

```
$ brew audit --new-formula tf2pulumi
tf2pulumi:
  * GitHub repository not notable enough (<30 forks, <30 watchers and <75 stars)
Error: 1 problem in 1 formula detected
```

Once we have a new release out I think it may still be worth submitting the pull request upstream even without meeting the notability requirements, since it is a companion tool to one already included.

Alternatively, we could update the `pulumi` formula to also install `tf2pulumi`.
