### ISSUE TITLE
Publish binaries for all platforms regularly

### ISSUE THREAD

**Issue by clstokes** [pulumi/tf2pulumi#119]
We currently only publish macOS and Linux binaries. We should publish Windows as well.

**Comment by TheFynx** [comment]
Not sure how you're currently pushing binaries, but there is a excellent tool for Golang called GoReleaser (<https://goreleaser.com/>) we use that build windows, linux, and macos archives. It also creates other packages such as deb, rpm, snap, brew, etc... 

If this seems like something you'd be interested in, I can create a PR or walk any of your devs through who are interested. (I'm also in the community slack).

**Comment by lukehoban** [comment]
> If this seems like something you'd be interested in, I can create a PR or walk any of your devs through who are interested. (I'm also in the community slack).

Definitely!  PRs very welcome - and happy to jump on a thread on #contributions on the community slack as well. We should be able to add a make target for this and script that into the Travis CI/CD setup for this repo.

**Comment by joeduffy** [comment]
Slight adjustment to the title. We haven't published any new updates since September, and generally [instruct people to install by building from source](https://github.com/pulumi/tf2pulumi#building-and-installation). As part of ensuring we publish Windows binaries, let's make sure we publish binaries for Linux and macOS also, consistently and regularly.
