### ISSUE TITLE
Support Terraform 0.13 (and 0.14, 0.15 and 1.0)

### ISSUE THREAD

**Issue by lukehoban** [pulumi/tf2pulumi#186]
We should make sure tf2pulumi can support the additions in the upcoming 0.13 release of Terraform. 

https://github.com/hashicorp/terraform/issues/25016

**Comment by stack72** [comment]
0.15-rc.2 hit just this week so I expect 0.15 to be an imminent release

**Comment by brogers-propstream** [comment]
So we ran into this issue when trying to choose an IAC platform. Our situation is that we have a vendor who will be building a bunch of terraform solutions for us. We were thinking of just allowing them to work in terraform and then convert their stuff to Pulumi. However, none of these templates can be easily converted since they are all 0.13 and beyond. 

This likely means that my company will decide not to use Pulumi at all, which is sad because the developers love it. 

At the end of the day, though, we expect that tools like this are updated regularly, if they are not, we must consider that an indication of poor product support for your flagship. 

Not trying to be mean or demanding, just trying to express how this particular issue potentially prevented pulumi from a potential sale - even though this particular utility is entirely open source.

**Comment by schmurfy** [comment]
I wanted to give pulumi a try but found out that my terraform 0.15 project cannot be converted :/
if terraform 0.12 is the last version to be fully supported it means this project is not that helpful for any currently maintained terraform configuration, 0.12 was released more than one year ago.

**Comment by dvins** [comment]
Sorry to ask, but is this still tracking for Q2 2022? The outdated Terraform support here is actually preventing adoption of Pulumi for shops like ours.

**Comment by Sharaf0** [comment]
Sorry to bother you, since we are already in 2023, any plans to fixing this anytime soon? it prevents adoption of Pulumi.

**Comment by Frassle** [comment]
New converter is tested against terraform 1.0 code.

**Comment by lukehoban** [comment]
The new `pulumi convert —from terraform` supports the vast majority of modern Terraform features. See more at https://www.pulumi.com/blog/converting-full-terraform-programs-to-pulumi/.
