### ISSUE TITLE
No instructions for installing missing plugin

### ISSUE THREAD

**Issue by braunsonm** [pulumi/tf2pulumi#237]
## Steps to reproduce

1. Have a Terraform project that uses the azurerm provider
2. `tf2pulumi --target-language typescript`
3. See error

Expected: According to the docs there should be a command for you to use to install the missing plugin. None is output here so I'm not sure how to continue. I tried installing the pulumi azure native plugin without luck.
Actual: The error doesn't provide any steps for solving the issue. `error: no resource plugin 'azurerm' found in the workspace or on your $PATH`

**Comment by infin8x** [comment]
Hi @braunsonm, sorry for the trouble. Since you're converting from Terraform, you'd need to use the older Terraform-based Classic Azure provider: `pulumi plugin install resource azure 4.7.0`. We'll keep this bug open to track improving the error message, as you suggest.

**Comment by ddellacosta** [comment]
Hi, encountering the same issue but with aws.

This is the first time I've used pulumi, which is being proposed as an alternative to our terraform infrastructure. That being the case, all I have done is attempt a conversion of my terraform config into pulumi, per https://www.pulumi.com/docs/guides/adopting/from_terraform/#converting-terraform-hcl-to-pulumi

I did not do any preliminary set up of AWS because as far as I can tell, everything required [here](https://www.pulumi.com/docs/intro/cloud-providers/aws/setup/) is already set up for me.

```shell
> tf2pulumi --target-language python
error: no resource plugin 'aws' found in the workspace or on your $PATH
> tf2pulumi --target-language python --allow-missing-plugins
error: no resource plugin 'aws' found in the workspace or on your $PATH
> pulumi version
v3.5.1
> pulumi plugin install resource aws
error: missing plugin version argument
>
```

I would attempt to install the aws plugin, but I have no idea what version number it expects, and even after poking around your docs and github org for half an hour I have no idea where to look this up.

**Comment by leezen** [comment]
@ddellacosta The version number is the version of a released version, i.e. https://github.com/pulumi/pulumi-aws/releases has the full list.

`pulumi plugin install resource aws v4.8.0`

**Comment by ddellacosta** [comment]
@leezen thanks!

**Comment by kmosher** [comment]
Hit the exact same error as referenced in @ddellacosta's [comment](https://github.com/pulumi/tf2pulumi/issues/237#issuecomment-864152437) (python pulumi project converting from terraform code interacting with AWS).

Solved by pip installing the `pulumi_aws` python package into the virtualenv created by `pulumi new`, (`./venv/bin/pip install pulumi_aws`), but the error was less than helpful in indicating that was the remedy.

**Comment by Frassle** [comment]
The [new converter](https://www.pulumi.com/blog/converting-full-terraform-programs-to-pulumi/) is both more tolerant to missing providers, but also should give the correct "pulumi plugin install" command in the warning about them missing.
