### ISSUE TITLE
Fix master build

### ISSUE THREAD

**Issue by stack72** [pulumi/tf2pulumi#247]
Build was broken recently on a PR and the PR was merged

**Comment by AaronFriel** [comment]
👍 on it, will have an update for you EOD

**Comment by AaronFriel** [comment]
It looks like there's a test flake due to some concurrency. To support this, referring to the logs from the original test run and retries:

1st run: TestASG and TestELB2 fail

2nd run: TestEIP and TestELB fail

3rd run: TestELB2 alone fails

4th run: TestASG alone fails

All tests failed with an error relating to "aws_security_group" "default", and it looks like a data race on manipulating that default group, which is specified in all four of the named tests and only in those four:

https://github.com/pulumi/tf2pulumi/blob/da4e6acb007c2fc5949f3e7b78e4ada9a61a23ee/tests/terraform/aws/asg/main.tf#L58

https://github.com/pulumi/tf2pulumi/blob/da4e6acb007c2fc5949f3e7b78e4ada9a61a23ee/tests/terraform/aws/eip/main.tf#L13

https://github.com/pulumi/tf2pulumi/blob/da4e6acb007c2fc5949f3e7b78e4ada9a61a23ee/tests/terraform/aws/elb/main.tf#L53

https://github.com/pulumi/tf2pulumi/blob/9f5ecb19c9200f9052f71b31cc09d19f5050fe48/tests/terraform/aws/elb2/main.tf#L49
