### ISSUE TITLE
Question: Can I keep hcl whilst running Pulumi on it?

### ISSUE THREAD

**Issue by gtmtech** [pulumi/tf2pulumi#276]
Hi I hope you dont mind asking a question here. 

I wondered if there is a translation library available for pulumi, where I can keep all my IAC as hcl code, and keep the DSL-not-code aspect, yet use Pulumi to actually run it. Therefore something that reads hcl and converts to Pulumi resources on the fly, rather than actively migrates the codebase to pulumi infra-as-software code. 

My ultimate goal is to keep code as HCL, but use Pulumi to run it, as Terraform cant handle my usecase but I think Pulumi can. 

Thanks

**Comment by iwahbe** [comment]
Hey @gtmtech. Thanks for opening this issue. It sounds like you're asking if you can use Pulumi as an execution engine for Terraform. Is that right?

For my own curiosity, what can you express in HCL that Terraform can't handle?

**Comment by gtmtech** [comment]
Hi @iwahbe  - we operate at quite a large scale across thousands of AWS accounts. The lack of dynamic providers in Terraform led us to use Terragrunt as an orchestrator and a dynamic provider generator so we can operate across multiple AWS acocunts at the same time, however we hit a limit due to the way Terraform creates a process per provider - with the process containing the whole aws provider. 

IE after about 200 accounts, the memory profile of a terraform run goes > 16Gb which makes it difficult to plan on laptops. 

It's not doing much here, we are doing a tiny piece of work on each account often, but unfortunately due to the way Terraform's code is structured this is memory prohibitive. 

I thought we might be able to leverage Pulumi as an alternative, and I thought that perhaps Pulumi might handle this case better out of the box, because it has support for dynamic providers anyway. Perhaps I could take away terragrunt and terraform and replace with Pulumi somehow. 

The difficulty with Pulumi is I dont really like the flexibility of a language based IAC manager, rather than an idiomatic DSL based IAC manager - in my experience teams which have access to a language can quickly create difficult-to-understand code, and one of the things I always liked about the DSL-nature of terraform is that code is always understandable no matter which teams you work in. 

I thought perhaps pulumi might have a HCL reader somewhere, which allows me to keep the constructs as terraform HCL, but run via a pulumi interpreter - particularly if things like tf2pulumi already exist which can understand HCL in the first place.

**Comment by jaxxstorm** [comment]
Hi @gtmtech - thanks for the thoughtful explanation!

I think the first thing to address is the difference between dynamic providers in Pulumi vs Terragrunt's dynamic providers. 

In **Terraform**, providers (ie, the mechanism by which you connect to a cloud account) are global in scope and don't allow creation of providers via any generation mechanism, meaning you can't use features like `dynamic` to generate providers.

Terragrunt works around this limitation by essentially copying the entirety of a terraform configuration (including the modules and `provider.tf` into multiple directories for each targeted account). I've seen lots of ways this can be done, but the generally mechanism used is Terragrunt's `generate` block. This obviously has the side effect that if you run `terragrunt` you'll get the result that it's actually invoking Terraform hundreds of times, which as you note can cause memory usage.

A **Pulumi** dynamic provider is slightly different - it's a mechanism by which you can create your own create/replace/update/diff inputs into a cloud provider. 

The distinction that it's different is important for the next part - the reason Pulumi doesn't have Terragrunt-style dynamic cloud providers because Pulumi doesn't need them. 

Pulumi's model allows you to instantiate providers at will - each provider is just another resource in the state. You can specify the provider easily. You can see an example of how that works here: https://github.com/jaxxstorm/pulumi-examples/blob/main/python/aws/ec2_providers_loop/__main__.py

There are a few other things that I think are important.

If you wish to use a DSL, [Pulumi's YAML](https://www.pulumi.com/blog/pulumi-yaml/) support is flexible enough to support DSL generation of the end YAML. You can even use HCL to do that, as detailed in [this blog post](https://leebriggs.co.uk/blog/2022/05/04/deploying-kubernetes-clusters-in-absurd-languages)

However, you may find that you might want to just use the native YAML concepts.

Ultimately, Pulumi _can_ handle your use case, but it doesn't use dynamic providers to do so. Pulumi also _sort of_ supports HCL ( as a YAML generator) but you lose access to lots of parts of the Pulumi ecosystem by using a generator like that.

**Comment by iwahbe** [comment]
@gtmtech Expanding a bit more about your performance concerns, I just ran a quick Pulumi program on my laptop to concurrently create 300 s3 buckets, each with their own provider. Everything worked fine, and I didn't have any memory issues.

<details>
<summary> Pulumi Program </summary>

This is my full pulumi program.

```go
package main

import (
	"fmt"

	"github.com/pulumi/pulumi-aws/sdk/v5/go/aws"
	"github.com/pulumi/pulumi-aws/sdk/v5/go/aws/s3"

	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

func main() {
	pulumi.Run(func(ctx *pulumi.Context) error {
		for i := 0; i < 300; i++ {
			name := fmt.Sprintf("aws-%d", i)
			p, err := aws.NewProvider(ctx, name, &aws.ProviderArgs{
				Region: pulumi.String("us-east-2"),
				DefaultTags: &aws.ProviderDefaultTagsArgs{
					Tags: pulumi.StringMap(map[string]pulumi.StringInput{
						"created by": pulumi.String(name),
					}),
				},
			})
			if err != nil {
				return err
			}
			bName := fmt.Sprintf("bucket-%d", i)
			_, err = s3.NewBucket(ctx, bName, nil, pulumi.Provider(p))
			if err != nil {
				return err
			}
		}
		return nil
	})
}
```

</details>

**Comment by gtmtech** [comment]
Thanks both for your informative answers, much appreciated!

**Comment by gtmtech** [comment]
@iwahbe not sure if this is your experience, but I ran your program, and it created one thread per process, each one taking up around 100Mb of memory - indeed took about 12Gb of memory on my system overall. 

I see that under the cover it creates terraform resources (or calls terraform libs) anyway, so I think I have the same issue with Pulumi as I do with terraform, albeit perhaps a slightly smaller binary is being fork()d

**Comment by gtmtech** [comment]
<img width="1228" alt="Screenshot 2023-06-01 at 20 22 48" src="https://github.com/pulumi/tf2pulumi/assets/2953949/7bdb3a2c-b980-4d5c-9d8c-90b5e90a6941">

**Comment by Frassle** [comment]
This repo is being archived, if this question is still pertinent raise it at github.com/pulumi/pulumi/issues.
