### ISSUE TITLE
Consider eliding names

### ISSUE THREAD

**Issue by joeduffy** [pulumi/tf2pulumi#43]
I noticed we very often generate names on the resource specs we generate. That is typically neither necessary nor desirable, due to the way in which we auto-name resources to minimize conflicts.

We should consider eliding name fields, particularly now that these code outputs are being emitted into our docs, which means that copy and pasting them is often going to lead to trouble.

**Comment by pgavlin** [comment]
This is probably a more cross-cutting feature: ideally we'd mark these fields as "name" fields s.t.`tf2pulumi` understands what is and isn't a name.

In the meantime, we could hack something up that just elides all name fields from the output and put it under a flag that is disabled by default.

**Comment by pgavlin** [comment]
> that is typically neither necessary nor desirable, due to the way in which we auto-name resources to minimize conflicts.

Thinking about this a bit more, it seems more likely that a naive implementation of this will be more likely to produce an invalid example than that a copy-pasted examples will cause a conflict. I'm going to bump this to M22 so that we have time to do the cross-cutting work required for `tf2pulumi` to understand what is and isn't autonamed.
