### ISSUE TITLE
Support the conversion of Terraform state files to Pulumi stacks.

### ISSUE THREAD

**Issue by pgavlin** [pulumi/tf2pulumi#46]
Just what it says on the tin. As a first cut, this could be as simple as emitting a checkpoint file that can be imported as well as a list of configuration key/value pairs.

**Comment by joeduffy** [comment]
@lukehoban I assume that what we'd want here is something that works in tandem with state importers generally. For example

- Use the tfstate file to get a list of IDs and types to import
- Use the tfvars file to create the destination stack/configuration

I assume we're not thinking of doing an entirely new import pathway? Or do we really think that just cracking and converting the state is easy enough and less error prone, that we would?

**Comment by lukehoban** [comment]
That's right.  There's actually three approaches that I've heard discussed to how we could address this:
1. Directly convert tfstate/tfvars to pulumi checkpoint/config.
2. Use tfstate to generate IDs and then use some form of `pulumi state import` to import these.  (No direct answer for config - this would have to be part of a two step process)
3. Have a mode of `tf2pulumi` that generates all resources with `import: id`, so that `pulumi up` on the resulting stack automatically adopts all resources.  This would use the tfstate to get the corresponding `id`s, but would not require any manualy steps beyond passing a flag to `tf2pulumi`.

I think all three are still cnadidates.  We need to get a little further on the specifics of `pulumi state import` and `import: id` to know exactly how good the E2E experience would be for (2) and (3), though if those can work, they would in theory result in a nice workflow.

**Comment by lukehoban** [comment]
The changes in #142 provide a script users can copy into their `tf2pulumi` generated project to adopt existing resources.  This effectively addresses this issue, although it requires a couple of manual steps (added in the README).  This is effectively an implementation of (3) above, and has worked well in practice with users we've worked with to adopt resources from existing large projects.

I suspect this is all we'll want to do here until we transition `tf2pulumi` to do full project generation (multiple files, correct package.json and Pulumi.yaml, etc.).

**Comment by lukehoban** [comment]
I've opened #143 to track some follow-ups - but the core support here is now available and documented in the README.
