### ISSUE TITLE
stage.value: NYI: terraform variables

### ISSUE THREAD

**Issue by StefanSchoof** [pulumi/tf2pulumi#68]
I tried to convert my terraform files to pulumi with tf2pulumi. I get the error `error: importing Terraform project graphs: stage.value: NYI: terraform variables`. I have no idea what the message means and how I can convert my project.

To reproduce, create a `Dockerfile` with the content:
```dockerfile
FROM golang as tf2pulumi

RUN go get -d github.com/pulumi/tf2pulumi/... 
RUN curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
RUN cd $(go env GOPATH)/src/github.com/pulumi/tf2pulumi \
 && dep ensure \                                   
 && go install github.com/pulumi/tf2pulumi

FROM node

COPY --from=tf2pulumi /go/bin/tf2pulumi /usr/local/bin
RUN git clone https://github.com/StefanSchoof/espresso.git
RUN curl -fsSL https://get.pulumi.com | sh
ENV PATH="/root/.pulumi/bin:${PATH}"
WORKDIR espresso/deploy
RUN pulumi login --local 
RUN pulumi new typescript --dir my-stack -y
RUN pulumi plugin install resource azure 0.16.9
RUN pulumi plugin install resource terraform-template 0.15.0      
RUN tf2pulumi
```

and then run `docker build .`

**Comment by pgavlin** [comment]
This is a limitation of the current version of `tf2pulumi`. Your project is referencing `terraform.workspace`, [here](https://github.com/StefanSchoof/espresso/blob/master/deploy/main.tf#L11), which `tf2pulumi` does not understand how to convert. Adding support for this should be straightfoward: a Pulumi stack is morally equivalent to a Terraform workspace, so that code should convert to something like `const stage = pulumi.getStack() === "prod" ? "" : pulumi.getStack();`.

Fixing this shouldn't take very long, but if you'd like to experiment in the meantime, you can convert your project by adding a variable `workspace` and moving all references to `terraform.workspace` to reference that variable instead. Note that you may also need to comment out the contents of `backend.tf`.

**Comment by pgavlin** [comment]
A fix is out for this issue, but your code also hits https://github.com/pulumi/tf2pulumi/issues/67. I will have a fix for that issue tomorrow.

**Comment by StefanSchoof** [comment]
Thanks for the quick fix.
